# highlighter: pygments
highlighter: rouge

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# markdown: kramdown
# kramdown:
#     input: GFM
#     syntax_highlighter: rouge

gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

#mode: dev
mode: product
url: https://xinray.github.io/
devurl: http://localhost:4000/
name: Ray
title: ray's blog
description: "XinRay's personal weblog, on coding or such stuff"

my:
    displayName: Ray
    realName: xinRay
    realName_cn: xinRay
    jobTitle: "程序员"
    contact:
        email: wxinray@outlook.com
        github: http://www.github.com/xinray
        linkedin: http://www.linkedin.com/in/wanxinray
        segmentfault: https://segmentfault.com/u/w_xin_ra_y
        stackoverflow: http://stackoverflow.com/users/6273960/ray
        csdn: http://blog.csdn.net/xin_ray

collections:
    qqGroupGuide:
        output: true

duoshuo_shortname: xinray
duoshuo_url: "http://wxinray.github.io"

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
    values:
        layout: markdownreader_bare
